### PR TITLE
README: update, add categories, clarify the review process for newcomers

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
README: update, add categories, clarify the review process for newcomers

I'm gonna make a weekly announcement via Bullhorn calling the community for review and add a link to the `Review process` paragraph not to repeat it each time.

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @gundalow @felixfontein @mariolenz

**Review by mariolenz — APPROVED** [review]
I wonder if it's really helpful to mention the [Resolved requests](https://github.com/ansible-collections/ansible-inclusion/discussions/categories/resolved-reviews) in `Existing requests`. But it doesn't hurt, either. The rest LGTM.

Thanks @Andersson007!

**Comment by Andersson007** [comment]
> I wonder if it's really helpful to mention the [Resolved requests](https://github.com/ansible-collections/ansible-inclusion/discussions/categories/resolved-reviews) in Existing requests. But it doesn't hurt, either. The rest LGTM.

@mariolenz , i wonder too:) Maybe it can be helpful in terms of "learning by example" for folks who'd like to see complete examples but won't reach the last paragraph where i put that link to Felix's example:)

**Comment by Andersson007** [comment]
@mariolenz thanks for reviewing!

**Pull request merged**
